version: '3.1'

services:

  db:
    image: postgres:alpine3.18
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  repetitor_bot:
    container_name: repetitor_bot
    image: repetitor_bot_image
    build:
      context: bot
      dockerfile: Dockerfile
    env_file:
      - ./.env